<?php
declare(strict_types=1);

use Migrations\AbstractSeed;

/**
 * All seed.
 */
class AllSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * https://book.cakephp.org/phinx/0/en/seeding.html
     *
     * @return void
     */
    public function run(): void
    {
        $data = [
            [
                'id' => 1,
                'name' => 'Admin',
                'description' => 'Administrator role',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'name' => 'User',
                'description' => 'Regular user role',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('roles');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'module_function' => 'Users:index',
                'name' => 'View User List',
                'description' => 'Allows viewing the list of users',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'module_function' => 'Users:create',
                'name' => 'Create User',
                'description' => 'Allows creating a new user',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 3,
                'module_function' => 'Users:delete',
                'name' => 'Delete User',
                'description' => 'Allows deleting a user',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 4,
                'module_function' => 'Users:view',
                'name' => 'View User Detail',
                'description' => 'Allows viewing detailed user information',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 5,
                'module_function' => 'Users:update',
                'name' => 'Update User',
                'description' => 'Allows updating user information',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 6,
                'module_function' => 'Categories:index',
                'name' => 'View Category List',
                'description' => 'Allows viewing the list of categories',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 7,
                'module_function' => 'Categories:create',
                'name' => 'Create Category',
                'description' => 'Allows creating a new category',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 8,
                'module_function' => 'Categories:delete',
                'name' => 'Delete Category',
                'description' => 'Allows deleting a category',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 9,
                'module_function' => 'Categories:view',
                'name' => 'View Category Detail',
                'description' => 'Allows viewing detailed category information',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:14:13'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('permissions');
        $table->insert($data)->save();
        
        $data = [
            [
                'id' => 1,
                'role_id' => 1,
                'permission_id' => 1,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'role_id' => 1,
                'permission_id' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 3,
                'role_id' => 1,
                'permission_id' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 4,
                'role_id' => 1,
                'permission_id' => 4,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 5,
                'role_id' => 1,
                'permission_id' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 6,
                'role_id' => 1,
                'permission_id' => 6,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 7,
                'role_id' => 1,
                'permission_id' => 7,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 8,
                'role_id' => 1,
                'permission_id' => 8,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 9,
                'role_id' => 1,
                'permission_id' => 9,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 10,
                'role_id' => 2,
                'permission_id' => 1,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 11,
                'role_id' => 2,
                'permission_id' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 12,
                'role_id' => 2,
                'permission_id' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 13,
                'role_id' => 2,
                'permission_id' => 4,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
            [
                'id' => 14,
                'role_id' => 2,
                'permission_id' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'created_by' => 'admin_user',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 20:15:01'),
                'updated_by' => 'admin_user',
                'delete_flg' => 0,
            ],
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('role_permissions');
        $table->insert($data)->save();
        
        $data = [
            [
                'id' => 1,
                'full_name' => 'Nguyễn Văn A',
                'password' => 'hashed_password_1',
                'birthday' => '1990-01-01 00:00:00',
                'sex' => 1,
                'email' => 'vana@example.com',
                'phone' => '123456789',
                'address' => '123 Đường ABC, Quận 1, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'full_name' => 'Trần Thị B',
                'password' => 'hashed_password_2',
                'birthday' => '1995-05-10 00:00:00',
                'sex' => 0,
                'email' => 'thib@example.com',
                'phone' => '987654321',
                'address' => '456 Đường XYZ, Quận 2, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 3,
                'full_name' => 'Lê Văn C',
                'password' => 'hashed_password_3',
                'birthday' => '1988-07-15 00:00:00',
                'sex' => 1,
                'email' => 'vanc@example.com',
                'phone' => '456123789',
                'address' => '789 Đường KLM, Quận 3, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 4,
                'full_name' => 'Phạm Thị D',
                'password' => 'hashed_password_4',
                'birthday' => '1992-03-20 00:00:00',
                'sex' => 0,
                'email' => 'thid@example.com',
                'phone' => '654987321',
                'address' => '101 Đường DEF, Quận 4, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 5,
                'full_name' => 'Hoàng Văn E',
                'password' => 'hashed_password_5',
                'birthday' => '1985-11-25 00:00:00',
                'sex' => 1,
                'email' => 'vane@example.com',
                'phone' => '321456987',
                'address' => '234 Đường GHI, Quận 5, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 6,
                'full_name' => 'Nguyễn Thị F',
                'password' => 'hashed_password_6',
                'birthday' => '1998-09-30 00:00:00',
                'sex' => 0,
                'email' => 'thif@example.com',
                'phone' => '789654123',
                'address' => '567 Đường LMN, Quận 6, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 7,
                'full_name' => 'Trần Văn G',
                'password' => 'hashed_password_7',
                'birthday' => '1993-02-05 00:00:00',
                'sex' => 1,
                'email' => 'vang@example.com',
                'phone' => '159357246',
                'address' => '890 Đường OPQ, Quận 7, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 8,
                'full_name' => 'Lê Thị H',
                'password' => 'hashed_password_8',
                'birthday' => '1987-04-12 00:00:00',
                'sex' => 0,
                'email' => 'thih@example.com',
                'phone' => '246813579',
                'address' => '112 Đường RST, Quận 8, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 9,
                'full_name' => 'Phạm Văn I',
                'password' => 'hashed_password_9',
                'birthday' => '1991-06-18 00:00:00',
                'sex' => 1,
                'email' => 'vani@example.com',
                'phone' => '369852741',
                'address' => '345 Đường UVW, Quận 9, TP.HCM',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            // Add more users as needed
        ];

        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('users');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'username' => 'admin1',
                'password' => '$2y$10$IGdNsR9Sqzuzz/ZBulW7aej1WPyrZGAPabmoSaB0PxLVJhB3XXuOO',
                'email' => 'admin@gmail.com',
                'birthday' => '1980-01-01 00:00:00',
                'sex' => 1,
                'phone' => '111111111',
                'address' => '789 Admin Street, Admin City',
                'full_name' => 'Nguyễn Văn Admin 1',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'role_id' => 1,
            ],
            [
                'id' => 2,
                'username' => 'admin2',
                'password' => 'hashed_admin_password_2',
                'email' => 'admin2@example.com',
                'birthday' => '1985-05-10 00:00:00',
                'sex' => 0,
                'phone' => '222222222',
                'address' => '456 Admin Avenue, Admin City',
                'full_name' => 'Trần Thị Admin 2',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'role_id' => 1,
            ],
            [
                'id' => 3,
                'username' => 'admin3',
                'password' => 'hashed_admin_password_3',
                'email' => 'admin3@example.com',
                'birthday' => '1982-07-15 00:00:00',
                'sex' => 1,
                'phone' => '333333333',
                'address' => '123 Admin Road, Admin City',
                'full_name' => 'Lê Văn Admin 3',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-05 00:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'role_id' => 1,
            ],
            // Add more admin users as needed
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('admin_users');
        $table->insert($data)->save();
        
        $data = [
            [
                'id' => 1,
                'name' => 'Piano',
                'description' => 'A large keyboard musical instrument.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'name' => 'Guitar',
                'description' => 'A string instrument which is played by plucking the strings.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 3,
                'name' => 'Violin',
                'description' => 'A string instrument played with a bow.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 4,
                'name' => 'Drums',
                'description' => 'A percussion instrument sounded by being struck with sticks or the hands.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Flute',
                'description' => 'A woodwind instrument made of a tube with holes along it that are stopped by the fingers or keys.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:30:36'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Saxophone',
                'description' => 'A woodwind instrument that sends out sounds through its curved, metal body.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Trumpet',
                'description' => 'A brass instrument commonly used in classical and jazz ensembles.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Cello',
                'description' => 'A large string instrument played with a bow, held between the knees.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Clarinet',
                'description' => 'A woodwind instrument with a single-reed mouthpiece.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Harp',
                'description' => 'A large string instrument which has strings perpendicular to the soundboard.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Accordion',
                'description' => 'A portable free-reed musical instrument.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Trombone',
                'description' => 'A brass instrument with a slide used to change the pitch.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Bass Guitar',
                'description' => 'A plucked string instrument similar in appearance and construction to an electric guitar.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 14,
                'name' => 'Oboe',
                'description' => 'A woodwind instrument with a double reed.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 15,
                'name' => 'Banjo',
                'description' => 'A string instrument with a thin membrane stretched over a frame or cavity to form a resonator.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 16,
                'name' => 'Mandolin',
                'description' => 'A string instrument in the lute family, generally with four courses of doubled strings.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 17,
                'name' => 'Ukulele',
                'description' => 'A small four-stringed guitar of Hawaiian origin.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 18,
                'name' => 'Synthesizer',
                'description' => 'An electronic musical instrument that generates audio signals.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 19,
                'name' => 'Xylophone',
                'description' => 'A musical instrument in the percussion family that consists of wooden bars struck by mallets.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 20,
                'name' => 'Harmonica',
                'description' => 'A small rectangular wind instrument with free reeds recessed in air slots from which tones are sounded by exhaling and inhaling.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:31:54'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
        ];
        
        // Ví dụ cho việc sử dụng trong framework CakePHP
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('categories');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'name' => 'Yamaha',
                'description' => 'A Japanese multinational corporation and conglomerate with a wide range of products and services.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 2,
                'name' => 'Fender',
                'description' => 'An American manufacturer of stringed instruments and amplifiers.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 3,
                'name' => 'Gibson',
                'description' => 'An American manufacturer of guitars, other musical instruments, and professional audio equipment.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 4,
                'name' => 'Steinway & Sons',
                'description' => 'A company that has been making world-class pianos since 1853.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 5,
                'name' => 'Roland',
                'description' => 'A Japanese manufacturer of electronic musical instruments, electronic equipment, and software.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 6,
                'name' => 'Korg',
                'description' => 'A Japanese multinational corporation that designs and manufactures electronic musical instruments.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 7,
                'name' => 'Ibanez',
                'description' => 'A Japanese guitar brand owned by Hoshino Gakki.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 8,
                'name' => 'Pearl',
                'description' => 'A multinational corporation based in Japan, with a wide range of percussion instruments.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 9,
                'name' => 'Marshall',
                'description' => 'An English company that designs and manufactures music amplifiers, speaker cabinets, and headphones.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 10,
                'name' => 'Casio',
                'description' => 'A Japanese multinational electronics manufacturing company.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 11,
                'name' => 'Bose',
                'description' => 'An American manufacturing company that predominantly sells audio equipment.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 12,
                'name' => 'Shure',
                'description' => 'An American audio products corporation.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 13,
                'name' => 'Behringer',
                'description' => 'A German musical equipment company.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 14,
                'name' => 'AKG',
                'description' => 'An Austrian manufacturer of headphones, microphones, and wireless audio systems.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 15,
                'name' => 'Boss',
                'description' => 'A manufacturer of effects pedals for electric guitar and bass guitar.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 16,
                'name' => 'DW Drums',
                'description' => 'An American drum and hardware manufacturing company.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 17,
                'name' => 'Taylor',
                'description' => 'An American guitar manufacturer.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 18,
                'name' => 'Gretsch',
                'description' => 'An American company that manufactures musical instruments.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 19,
                'name' => 'Epiphone',
                'description' => 'An American musical instrument manufacturer.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 20,
                'name' => 'Mapex',
                'description' => 'A Taiwanese drum brand.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 21,
                'name' => 'Focal',
                'description' => 'A French brand, which has been designing and manufacturing high fidelity audio products since 1979.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 22,
                'name' => 'Martin',
                'description' => 'An American guitar manufacturer established in 1833.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 23,
                'name' => 'Paiste',
                'description' => 'A Swiss manufacturer and designer of cymbals.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 24,
                'name' => 'Ludwig',
                'description' => 'An American manufacturer of percussion products and accessories.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 25,
                'name' => 'Sabian',
                'description' => 'A Canadian cymbal manufacturer.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 26,
                'name' => 'Zildjian',
                'description' => 'An American cymbal manufacturer.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 27,
                'name' => 'Rode',
                'description' => 'An Australian-based designer and manufacturer of microphones, related accessories, and audio software.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 28,
                'name' => 'Peavey',
                'description' => 'An American musical equipment company.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 29,
                'name' => 'Audio-Technica',
                'description' => 'A Japanese company that designs and manufactures professional microphones, headphones, phonographic magnetic cartridges, and other audio equipment.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 30,
                'name' => 'Squier',
                'description' => 'A company owned by Fender Musical Instruments Corporation.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 31,
                'name' => 'Kawai',
                'description' => 'A musical instrument manufacturing company headquartered in Hamamatsu, Shizuoka, Japan.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 32,
                'name' => 'Ernie Ball',
                'description' => 'An American manufacturer of guitar strings and accessories.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 33,
                'name' => 'Klipsch',
                'description' => 'An American loudspeaker company based in Indianapolis, Indiana.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 34,
                'name' => 'ESP Guitars',
                'description' => 'A Japanese guitar manufacturer, primarily focused on the production of electric guitars and basses.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 35,
                'name' => 'Mackie',
                'description' => 'An American company that produces professional audio equipment.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 36,
                'name' => 'Tama Drums',
                'description' => 'A brand of drum kits and hardware manufactured and marketed by the Japanese musical instrument company, Hoshino Gakki.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 37,
                'name' => 'JBL',
                'description' => 'An American company that manufactures audio equipment, including loudspeakers and headphones.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 38,
                'name' => 'Line 6',
                'description' => 'A manufacturer of digital modeling guitars, amplifiers (amplifier modeling) and related electronic equipment.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 39,
                'name' => 'Sennheiser',
                'description' => 'A German privately held audio company specializing in the design and production of a wide range of audio products.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            [
                'id' => 40,
                'name' => 'PRS Guitars',
                'description' => 'An American guitar and amplifier manufacturer.',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
            ],
            ['id' => 41, 'name' => 'Bose', 'description' => 'An American manufacturing company that predominantly sells audio equipment.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 42, 'name' => 'Shure', 'description' => 'An American audio products corporation.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 43, 'name' => 'Behringer', 'description' => 'A German musical equipment company.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 44, 'name' => 'AKG', 'description' => 'An Austrian manufacturer of headphones, microphones, and wireless audio systems.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 45, 'name' => 'Boss', 'description' => 'A manufacturer of effects pedals for electric guitar and bass guitar.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 46, 'name' => 'DW Drums', 'description' => 'An American drum and hardware manufacturing company.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 47, 'name' => 'Taylor', 'description' => 'An American guitar manufacturer.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 48, 'name' => 'Gretsch', 'description' => 'An American company that manufactures musical instruments.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 49, 'name' => 'Epiphone', 'description' => 'An American musical instrument manufacturer.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 50, 'name' => 'PRS Guitars', 'description' => 'An American guitar manufacturer founded by luthier Paul Reed Smith.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 51, 'name' => 'Zildjian', 'description' => 'An American cymbal manufacturer.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 52, 'name' => 'Sabian', 'description' => 'A Canadian cymbal manufacturing company.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 53, 'name' => 'M-Audio', 'description' => 'An American company that designs and markets digital audio and MIDI solutions for electronic musicians.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 54, 'name' => 'Audio-Technica', 'description' => 'A Japanese company that designs and manufactures professional microphones, headphones, phonographic magnetic cartridges, and other audio equipment.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0],
            ['id' => 55, 'name' => 'Sennheiser', 'description' => 'A German privately-held audio company specializing in the design and production of a wide range of high-fidelity products.', 'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'created_by' => 'admin', 'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 14:45:29'), 'updated_by' => 'admin', 'delete_flg' => 0]        
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('brands');
        $table->insert($data)->save();
        
        $data = [
            [
                'id' => 7,
                'name' => 'Kawai BL-31 SPECIAL',
                'description' => 'Đàn Piano Kawai BL31 là dòng sản phẩm được đánh giá cao trong học tập, tập luyện đàn piano của thương hiệu Kawai. Nó là cây đàn piano cũ được rất nhiều trường đào tạo âm nhạc lựa chọn để sử dụng tại Nhật.',
                'price' => 33000000,
                'tax' => 4,
                'max_quantity' => 100,
                'type' => 1,
                'start_date' => '2024-07-07 12:51:49',
                'end_date' => '2025-07-07 12:51:49',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 1,
                'brand_id' => 1,
            ],
            [
                'id' => 8,
                'name' => 'Casio CT-X800',
                'description' => 'Đàn organ Casio CT-X800 thuộc dòng CT-X Series của Casio. Đàn có thiết kế màn hình LCD rõ ràng, hữu ích, có đèn nền giúp người chơi thuận tiện khi trình diễn hoặc tập đàn.',
                'price' => 6520000,
                'tax' => 3,
                'max_quantity' => 100,
                'type' => 2,
                'start_date' => '2024-07-07 12:51:49',
                'end_date' => '2025-07-14 12:51:49',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 2,
                'brand_id' => 2,
            ],
            [
                'id' => 9,
                'name' => 'Guitar Cordoba Stage',
                'description' => 'Guitar Cordoba Stage có tông đàn đúng chuẩn, Mid’ed. Sẵn sàng cho các kích thước sân khấu và phòng thu khác nhau. Mid’ed là sound âm thanh sẵn sàng cho việc đặt Micro thu Guitar.',
                'price' => 10900000,
                'tax' => 3,
                'max_quantity' => 100,
                'type' => 3,
                'start_date' => '2024-07-07 13:17:33',
                'end_date' => '2025-07-07 13:17:33',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 3,
                'brand_id' => 3,
            ],
            [
                'id' => 10,
                'name' => 'Piano Kawai NS15',
                'description' => 'Kawai NS15 là cây đàn piano được sản xuất trong những năm từ 1980 - 1990,  với công nghệ tiên tiến từ hãng Kawai cùng với đội ngũ kỹ thuật viên giàu kinh nghiệm đã tạo nên một thiết kế hoàn hảo về kiểu dáng và âm thanh.',
                'price' => 40000000,
                'tax' => 3,
                'max_quantity' => 100,
                'type' => 1,
                'start_date' => '2024-07-07 13:19:32',
                'end_date' => '2025-07-07 13:19:32',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 1,
                'brand_id' => 1,
            ],
            [
                'id' => 11,
                'name' => 'Casio CT-X800',
                'description' => 'Đàn organ Casio CT-X800 thuộc dòng CT-X Series của Casio. Đàn có thiết kế màn hình LCD rõ ràng, hữu ích, có đèn nền giúp người chơi thuận tiện khi trình diễn hoặc tập đàn.',
                'price' => 6520000,
                'tax' => 1,
                'max_quantity' => 100,
                'type' => 2,
                'start_date' => '2024-07-07 13:26:37',
                'end_date' => '2025-07-07 13:26:37',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 2,
                'brand_id' => 2,
            ],
            [
                'id' => 12,
                'name' => 'Casiotone LK-S250',
                'description' => 'Casiotone LK-S250 là một model đàn được phát triển nâng cấp từ dòng sản phẩm Organ phím sáng vô cùng thành công của hãng này trước đó. Ở lần ra mắt năm nay, sản phẩm hứa hẹn mang đến cho người chơi những trải nghiệm tuyệt vời nhất.\r\nĐàn Organ Casiotone LK-S250 có thiết kế siêu mỏng, thời trang. Cây đàn có kích thước lần lượt là 930cm x 256cm x 73mm, trọng lượng 3,4kg. Với kích thước này giúp người chơi dễ dàng mang theo bất cứ nơi đâu. Casiotone LK-S250 còn được thiết kế phần tay cầm phía trên đầu đàn, đảm bảo việc di chuyển an toàn và nhanh chóng cho bất kì ai.\r\n\r\nSo với những model đàn Light Keyboard trước đây của Casio, LK-S250 có thời lượng pin sử dụng dài hơn, lên đến 16 giờ ( điều này không tuyệt đối vì còn tuỳ thuộc vào hiệu suất chơi, nếu bạn nhỏ chơi đàn liên tục  với những phong cách cần điều chỉnh, phối hợp nhiều thì năng lượng pin sẽ tiêu hao nhanh hơn).',
                'price' => 5700000,
                'tax' => 2,
                'max_quantity' => 100,
                'type' => 0,
                'start_date' => '2024-07-07 12:51:49',
                'end_date' => '2025-07-07 13:17:33',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
                'category_id' => 3,
                'brand_id' => 33,
            ],
        ];

        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('products');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 86,
                'product_id' => 7,
                'name' => 'White',
                'value' => '#FFFFFF',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 87,
                'product_id' => 7,
                'name' => 'Red',
                'value' => '#FF0000',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 88,
                'product_id' => 7,
                'name' => 'Yellow',
                'value' => '#FFFF00',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 89,
                'product_id' => 7,
                'name' => 'Gray',
                'value' => '#808080',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 90,
                'product_id' => 8,
                'name' => 'White',
                'value' => '#FFFFFF',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 91,
                'product_id' => 8,
                'name' => 'Red',
                'value' => '#FF0000',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 92,
                'product_id' => 8,
                'name' => 'Yellow',
                'value' => '#FFFF00',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 93,
                'product_id' => 8,
                'name' => 'Gray',
                'value' => '#808080',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 94,
                'product_id' => 9,
                'name' => 'M',
                'value' => '151cmx121cmx63cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 95,
                'product_id' => 9,
                'name' => 'L',
                'value' => '161cmx131cmx73cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 96,
                'product_id' => 9,
                'name' => 'XL',
                'value' => '181cmx151cmx93cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 97,
                'product_id' => 10,
                'name' => 'M',
                'value' => '151cmx121cmx63cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 98,
                'product_id' => 10,
                'name' => 'L',
                'value' => '161cmx131cmx73cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 99,
                'product_id' => 10,
                'name' => 'XL',
                'value' => '181cmx151cmx93cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 100,
                'product_id' => 11,
                'name' => '1/2',
                'value' => '53cm-54,7cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 101,
                'product_id' => 11,
                'name' => '1/4',
                'value' => '47,2cm-48,7cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 102,
                'product_id' => 11,
                'name' => '3/4',
                'value' => '59,5cm-61,4cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 103,
                'product_id' => 11,
                'name' => '4/4',
                'value' => '63cm-65cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 104,
                'product_id' => 12,
                'name' => '1/2',
                'value' => '53cm-54,7cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 105,
                'product_id' => 12,
                'name' => '1/4',
                'value' => '47,2cm-48,7cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 12:51:49'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 106,
                'product_id' => 12,
                'name' => '3/4',
                'value' => '59,5cm-61,4cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
            [
                'id' => 107,
                'product_id' => 12,
                'name' => '4/4',
                'value' => '63cm-65cm',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:26:37'),
                'created_by' => 'SangTT',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 13:17:33'),
                'updated_by' => 'SangTT',
                'delete_flg' => 0,
            ],
        ];
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('properties');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'piority' => 1,
                'path_image' => 'banner1.jpg',
                'url_decription' => 'http://example.com/1',
                'start_date' => '2023-01-01 00:00:00',
                'end_date' => '2023-01-31 23:59:59',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-01 10:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-01 10:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0
            ],
            [
                'id' => 2,
                'piority' => 2,
                'path_image' => 'banner2.jpg',
                'url_decription' => 'http://example.com/2',
                'start_date' => '2023-02-01 00:00:00',
                'end_date' => '2023-02-28 23:59:59',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-02 11:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-02 11:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0
            ],
            // Add more entries as needed
        ];
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('image_banners');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 151,
                'piority' => 1,
                'path_image' => 'image1.jpg',
                'start_date' => '2023-01-01 10:00:00',
                'end_date' => '2024-01-01 10:00:00',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-01 10:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-01 10:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'product_id' => 7
            ],
            [
                'id' => 152,
                'piority' => 2,
                'path_image' => 'image2.jpg',
                'start_date' => '2023-01-01 10:00:00',
                'end_date' => '2024-01-01 10:00:00',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-02 11:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-02 11:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'product_id' => 7
            ],
            [
                'id' => 153,
                'piority' => 1,
                'path_image' => 'image3.jpg',
                'start_date' => '2023-01-01 10:00:00',
                'end_date' => '2024-01-01 10:00:00',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-03 12:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-03 12:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'product_id' => 8
            ],
            [
                'id' => 154,
                'piority' => 1,
                'path_image' => 'image4.jpg',
                'start_date' => '2023-01-01 10:00:00',
                'end_date' => '2024-01-01 10:00:00',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-04 13:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-04 13:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'product_id' => 9
            ],
            [
                'id' => 155,
                'piority' => 1,
                'path_image' => 'image5.jpg',
                'start_date' => '2023-01-01 10:00:00',
                'end_date' => '2024-01-01 10:00:00',
                'created_at' => new \Cake\I18n\FrozenTime('2023-01-05 14:00:00'),
                'created_by' => 'admin',
                'updated_at' => new \Cake\I18n\FrozenTime('2023-01-05 14:00:00'),
                'updated_by' => 'admin',
                'delete_flg' => 0,
                'product_id' => 12
            ],
            // Add more entries as needed
        ];
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('image_products');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'user_id' => 1,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:03:45'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:03:45'),
                'updated_by' => '1',
                'delete_flg' => 0
            ],
            [
                'id' => 2,
                'user_id' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'updated_by' => '1',
                'delete_flg' => 0
            ],
            [
                'id' => 3,
                'user_id' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:25'),
                'updated_by' => '1',
                'delete_flg' => 0
            ],
            [
                'id' => 4,
                'user_id' => 4,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:06:27'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:06:27'),
                'updated_by' => '1',
                'delete_flg' => 0
            ],
            [
                'id' => 5,
                'user_id' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'updated_by' => '1',
                'delete_flg' => 0
            ],
            // Add more entries as needed
        ];

        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('carts');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 17,
                'quantity' => 1,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:03:45'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:03:45'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 7,
                'cart_id' => 1
            ],
            [
                'id' => 18,
                'quantity' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 8,
                'cart_id' => 1
            ],
            [
                'id' => 19,
                'quantity' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:15'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 7,
                'cart_id' => 2
            ],
            [
                'id' => 20,
                'quantity' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:05:25'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 9,
                'cart_id' => 1
            ],
            [
                'id' => 21,
                'quantity' => 4,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:06:27'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:06:27'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 10,
                'cart_id' => 3
            ],
            [
                'id' => 22,
                'quantity' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 12,
                'cart_id' => 1
            ],
            [
                'id' => 23,
                'quantity' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'updated_by' => '1',
                'delete_flg' => 1,
                'product_id' => 8,
                'cart_id' => 1
            ],
            [
                'id' => 24,
                'quantity' => 5,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'created_by' => '1',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 21:07:25'),
                'updated_by' => '1',
                'delete_flg' => 0,
                'product_id' => 7,
                'cart_id' => 1
            ],
            // Add more entries as needed
        ];
        
        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('cart_details');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 1,
                'total_amount' => 0,
                'payment_div' => '01',
                'delivery_div' => '01',
                'address' => '',
                'status' => '01',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'user_id' => 1
            ],
            [
                'id' => 2,
                'total_amount' => 30000,
                'payment_div' => '01',
                'delivery_div' => '01',
                'address' => '',
                'status' => '01',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'user_id' => 2
            ],
            [
                'id' => 3,
                'total_amount' => 30000,
                'payment_div' => '02',
                'delivery_div' => '01',
                'address' => '',
                'status' => '01',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'user_id' => 3
            ],
            [
                'id' => 4,
                'total_amount' => 30000,
                'payment_div' => '02',
                'delivery_div' => '01',
                'address' => '',
                'status' => '01',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'user_id' => 4
            ],
            [
                'id' => 5,
                'total_amount' => 30000,
                'payment_div' => '02',
                'delivery_div' => '01',
                'address' => '',
                'status' => '01',
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-07 19:03:52'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'user_id' => 5
            ],
            // Add more entries as needed
        ];
        

        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('orders');
        $table->insert($data)->save();

        $data = [
            [
                'id' => 16,
                'price' => 5000,
                'quantity' => 2,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'product_id' => 7,
                'order_id' => 1
            ],
            [
                'id' => 17,
                'price' => 50000,
                'quantity' => 4,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'product_id' => 8,
                'order_id' => 1
            ],
            [
                'id' => 18,
                'price' => 5000,
                'quantity' => 1,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'product_id' => 9,
                'order_id' => 1
            ],
            [
                'id' => 19,
                'price' => 5000,
                'quantity' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'product_id' => 12,
                'order_id' => 2
            ],
            [
                'id' => 20,
                'price' => 15000,
                'quantity' => 3,
                'created_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'created_by' => 'NhanVP',
                'updated_at' => new \Cake\I18n\FrozenTime('2024-07-08 03:52:54'),
                'updated_by' => 'NhanVP',
                'delete_flg' => 0,
                'product_id' => 11,
                'order_id' => 2
            ],
            // Add more entries as needed
        ];
        

        foreach ($data as &$row) {
            $row['created_at'] = $row['created_at']->format('Y-m-d H:i:s');
            $row['updated_at'] = $row['updated_at']->format('Y-m-d H:i:s');
        }
        $table = $this->table('order_details');
        $table->insert($data)->save();
    }
}
